app:
  image: 'firstandthird/node:8.9-3-dev'
  volumes:
    - ".:/home/app/src"
    - "/var/run/docker.sock:/var/run/docker.sock"
    #- "$HOME/.docker:/home/app/.docker"
  ports:
    - '8079:8080'
  environment:
    CONFIG_PATH: '/home/app/src/example-config'
    DEBUG:
    VERBOSE_DEBUG:
    DOMAIN:
    SECRET:
    MONITOR_FOR:
    # SLACK_HOOK:
    #  SLACK_NAME:
    DOCKERHUB_AUTH:
