app:
  image: 'firstandthird/node:8.8-dev-root'
  volumes:
    - ".:/home/app/src"
    - "/var/run/docker.sock:/var/run/docker.sock"
    #- "$HOME/.docker:/home/app/.docker"
  ports:
    - '8081:8080'
  environment:
    DEBUG: 1
    CONFIG_PATH: '/home/app/src/example-config'
    SECRET:
    SLACK_HOOK:
    SLACK_NAME:
    DOCKERHUB_AUTH:


