app:
  build: '.'
  command: 'npm run dev'
  dockerfile: 'DockerfileDev'
  volumes:
    - ".:/home/app/src"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$HOME/.docker:/home/app/.docker"
  environment:
    VIRTUAL_HOST: 'autodeploy.*'
    SECRET: 'abc123'
    SLACK_HOOK:
    SWARM_MODE:

