_url: 'http://{{domain}}'
_type: 'compose'
traefik:
  image: 'traefik:v1.5.2-alpine'
  command:
    - '--docker.domain={{domain}}'
    - '--loglevel=WARN'
    - '--docker'
    - '--docker.swarmmode'
    - '--docker.domain=firstandthird.com'
    - '--docker.watch'
    - '--retry.attempts=2'
    - '--web'
    - '--accesslog'
    - '--entrypoints=Name:http Address::80'
    - '--entrypoints=Name:https Address::443 TLS'
    - '--defaultentrypoints=http,https'
    - '--acme.entrypoint=https'
    - '--acme.email=hi@firstandthird.com'
    - '--acme.storage=/etc/traefik/acme/acme.json'
    - '--acme.ondemand=true'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
  networks:
    - traefik-net
  ports:
    - '80:80'
    - '8080:8080'
    - '443:443'
  deploy:
    mode: global
    update_config:
      delay: 5s
      failure_action: 'rollback'
      order: start-first
    placement:
      constraints:
        - node.role == manager
